### ISSUE TITLE
More licenses?

### ISSUE THREAD

**Issue by easyaspi314** [PSDev/LicensesDialog#40]
I was noticing that there were a few licenses missing. Here are some licenses I would like to see:
- LGPL v3
- Mozilla Public License v2
- Creative Commons
- Eclipse Public License 1.0

Looking at the code, I found that to register a new license, I need to call `LicensesResolver.registerLicense(new MyLicense());`. This is really hidden and there needs to be more documentation.

**Comment by hameno** [comment]
Sure, feel free to post a pull request ;)

**Comment by easyaspi314** [comment]
OK! By the way, I noticed that in the Gradle build, you use getFullText and
getSummaryText, but in the source you use a different signature. Mind if I
update that?

**Comment by hameno** [comment]
What Gradle build do you mean?

**Comment by easyaspi314** [comment]
From Licenses.java: public abstract String readSummaryTextFromResources(
final Context context); public abstract String readFullTextFromResources(
final Context context);

**Comment by hameno** [comment]
Yeah, thats because they are unreleased changes. Nothing to change.
