### ISSUE TITLE
v-13 Support Library version

### ISSUE THREAD

**Issue by alextel69** [PSDev/LicensesDialog#55]
When using Support Library v-13 getSupportFragmentManager() is not accessible, thus I can't show LicensesFragment

**Comment by hameno** [comment]
?

**Comment by alextel69** [comment]
@hameno updated description

**Comment by hameno** [comment]
Sorry, I won't support that, no one should use the platforms fragment version, always use support-v4 fragments to avoid bugs in the framework.
