### ISSUE TITLE
Use com.google.code.findbugs:jsr305:2.0.1 instead of 3.0.0

### ISSUE THREAD

**Issue by rocboronat** [PSDev/LicensesDialog#57]
When adding Espresso support to test an app with instrumentation tests, LicensesDialog dependencies conflict with Espresso ones. The thing is that is really simple to fix: let's depend on jsr305 version 2.0.1, instead of the last one, as Espresso does.

Thank you! :·)

**Comment by hameno** [comment]
Will fix it in the future, just exclude the dependency for now

**Comment by rocboronat** [comment]
Thanks @hameno :·)

If someone arrives here for the same reason, add the LicensesDialog using this alternative line:

``
compile ('de.psdev.licensesdialog:licensesdialog:1.8.0'){
        exclude module: 'jsr305'
    }
``
