### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by simplaapliko** [PSDev/LicensesDialog#58]
Hi Philip,
Question - do you have plans to publish new release in the near future?
There were 5 commits since the last release, and I personally interested in #53 and #54.

thanks,
Oleg

**Comment by hameno** [comment]
Not within the next month, but you can use the Snapshots

**Comment by simplaapliko** [comment]
thanks for the tip,
Snapshot is what I needed!

**Comment by hameno** [comment]
I've just released version 1.8.1

**Comment by simplaapliko** [comment]
thank you!
