### ISSUE TITLE
setNotices shouldn't throw exception

### ISSUE THREAD

**Issue by Sloy** [PSDev/LicensesDialog#59]
The method setNotices() in LicensesDialogFragment.Builder declares `throws Exception`, but it's not performing absolutely anything in the method's body, so the throw declaration is not needed.

This method is forcing the user to catch a generic unknown exception without reason. Could you remove it to clean-up our code?

Thanks!

**Comment by hameno** [comment]
Ops, yes that might have been because I wanted to implement a check there. Anyway, you right, its obsolete. Can you do a PR with that change?

**Comment by Sloy** [comment]
Ok will do
