### ISSUE TITLE
missing legal acknowledgement in the dialog

### ISSUE THREAD

**Issue by mars3142** [PSDev/LicensesDialog#69]
I can only add the license, but there is no way to add the notices. 

E.g. watch at https://github.com/h6ah4i/android-advancedrecyclerview - this isn't possible right now with your library or miss I something?

**Comment by hameno** [comment]
I'm not sure what you mean. Notices are automatically displayed based on the license you define in the licenses.xml, see the sample app how it works.

**Comment by mars3142** [comment]
Did you open the linked project? Where would you add the content of the NOTICE file? The LICENSE file is clear, but not the NOTICE.

**Comment by hameno** [comment]
Yes, I opened it. It is not necessary to add those files, they follow a common pattern and are auto-generated. Please take a look at the sample app.

**Comment by mars3142** [comment]
But this **notices** can be everything and not just **autogenerated** as you said. Okay, will find another way to use it.

**Comment by hameno** [comment]
You can always add your own license class if it has a custom notice text. All included licenses have the default notice texts that the license requires.
