### ISSUE TITLE
no such license available

### ISSUE THREAD

**Issue by Scrounger** [PSDev/LicensesDialog#72]
I get the error 'no such license available' for the following two license:
`Eclipse Public License 1.0`
`Mozilla Public License 2.0`

**Comment by hameno** [comment]
I haven't had time to release a new version. Those licences were added after the last release. For now you can use the latest snapshot:

Gradle:

    compile('de.psdev.licensesdialog:licensesdialog:1.82-SNAPSHOT')

Maven:

```
<dependency>
  <groupId>de.psdev.licensesdialog</groupId>
  <artifactId>licensesdialog</artifactId>
  <version>1.8.2-SNAPSHOT</version>
  <type>aar</type>
</dependency>
```

You need to add https://oss.sonatype.org/content/repositories/snapshots as a repository.
