### ISSUE TITLE
Can LicenseDialog dynamically retrieve licenses from dependencies?

### ISSUE THREAD

**Issue by JimVanG** [PSDev/LicensesDialog#78]
Hello,

I'm curious if LicenseDialog has the ability to pull in the licenses from an app's dependencies dynamically? 

Right now it appears that the end developer needs to manually define their dependencies in a static `xml` file, or create `Notice` objects programmatically. Both of which require the developer to manually and statically add in every license from every dependency in their project.

Please correct me if I'm wrong! I'd love to use LicenseDialog in my app, but I kind of need the licenses to be retrieved dynamically during the Gradle build.

**Comment by hameno** [comment]
Currently now, no. That would also only work if the dependency declared the license in the pom.

**Comment by JimVanG** [comment]
Alright, thanks for the quick reply!

I'm looking into tools that can dynamically retrieve licenses. I've found this Gradle plugin: https://github.com/cookpad/license-tools-plugin?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3627

But unfortunately it's not a completely automated thing... It helps, but you still need to go in an manually include some information about the dependencies before you can generate a "licenses.html" file for your app to use at runtime.
