### ISSUE TITLE
Change License URLs from http:// to https://

### ISSUE THREAD

**Issue by jpstotz** [PSDev/LicensesDialog#82]
I noticed that all the license implementations in `de.psdev.licensesdialog.licenses` return the insecure http:// urls when calling `getUrl()`. 
From my perspective the urls should be changed to `https://` as all the major version provider like Mozilla, Eclipse, Apache, ... have changed their primary site to https:// - therefore IMHO the urls in this library should be adapted, too.

**Comment by jpstotz** [comment]
Addendum: This also applies to the psdev url in class `de.psdev.licensesdialog.LicensesDialog`
`new Notice("LicensesDialog", "http://psdev.de/LicensesDialog", ...`

**Comment by hameno** [comment]
Good Idea, would you be willing to create a Pull Request?

**Comment by jpstotz** [comment]
Sorry I can't do that.

**Comment by sergioschoon** [comment]
Ola
